apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: fakeapp
  annotations:
    github.com/project-slug: RaizaClaudino/fakeapp
    argocd/app-name: reducio-live
    backstage.io/techdocs-ref: url:https://www.google.com/
spec:
  type: service
  lifecycle: production
  owner: RaizaClaudino
  providesApis:
    - fake-api
  partOf:
    - fake-system
  consumesApi: fake-api-second
  dependsOn: [fake-system-second]
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: fake-api
  tags: [externally-exposed]
  description: API test
spec:
  type: openapi
  definition:
    $text: https://github.com/RaizaClaudino/fakeapp/blob/main/openapi.yaml
  lifecycle: production
  owner: fake-saquad
  system: fake-system

